### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by BooLightning**
This is just a template

### CODE REVIEW

**Comment by BooLightning** [comment]
I think your projects should have some security.

**Comment by RedZRosebud** [comment]
> I think your projects should have some security.

I guess your right, GitHub is CONFUSING

**Comment by BooLightning** [comment]
Yeah

**Comment by BooLightning** [comment]
Could you please click “Merge pull request”?

**Comment by BooLightning** [comment]
It’s the green button.

**Comment by BooLightning** [comment]
Hello?

**Comment by BooLightning** [comment]
The green button?

**Comment by BooLightning** [comment]
“Merge pull request”?

**Pull request merged**
